# .streamlit/secrets.toml

[snowflake]
account = "wypdwwk-ns10102"
user = "ADRIANRAMOS"
password = "#SDGmadrid_2026"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"